### ISSUE TITLE
problem with the MSVC default configuration?

### ISSUE THREAD

**Issue by divinity76** [dtroitskiy/FoF-editor#1]
just downloaded and tried to build with msvc 2013, i got this error: 
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(887,5): error MSB3191: Unable to create directory "C:\Users\hanshenrik\Desktop\OT\NewEditor-master\C:\Users\hanshenrik\Desktop\OT\NewEditor-master\obj\Release". The given path's format is not supported.

i guess you got a problem with the msvc configuration

**Comment by dtroitskiy** [comment]
Hi divinity76,

In fact, I develop this editor for one of my work projects and I didn't expect somebody else will use it, at least in near future =) However, I'll be glad if someone will do so and I'm ready to provide some help and assistance.

I need to warn, that editor is still in development, basic features work, but there still may be crashes and bugs. There's also feature to automatically generate resources for Remere's Map Editor and it hasn't been tested thoroughly yet. Undo / redo is also not working for everything yet. And so on.

About issue you described, need to check, I see some weird path concatenation occurred, but for me it works. While I mostly build on Linux, I also make win32 builds from time to time and didn't see such issue.

**Comment by dtroitskiy** [comment]
Although I didn't check this problem yet, I need to close this as repository may become private soon.
